//
// dx/system_call_vectors.h
//

#ifndef _SYSTEM_CALL_VECTORS_H
#define _SYSTEM_CALL_VECTORS_H


#define SYSTEM_CALL_VECTOR_RECEIVE_MESSAGE			80
#define SYSTEM_CALL_VECTOR_SEND_AND_RECEIVE_MESSAGE	81
#define SYSTEM_CALL_VECTOR_SEND_MESSAGE				82
#define SYSTEM_CALL_VECTOR_DELETE_MESSAGE			83

#define SYSTEM_CALL_VECTOR_CONTRACT_ADDRESS_SPACE	90
#define SYSTEM_CALL_VECTOR_CREATE_ADDRESS_SPACE		91
#define SYSTEM_CALL_VECTOR_DELETE_ADDRESS_SPACE		92
#define SYSTEM_CALL_VECTOR_EXPAND_ADDRESS_SPACE		93

#define SYSTEM_CALL_VECTOR_CREATE_THREAD			100
#define SYSTEM_CALL_VECTOR_DELETE_THREAD			101

#define SYSTEM_CALL_VECTOR_MAP_DEVICE				110
#define SYSTEM_CALL_VECTOR_UNMAP_DEVICE				111

//@shutdown/reboot?
//@manipulate security token?

#endif
