#
# Makefile
#


# Include the default definitions + configuration
include $(DX_ROOT_DIR)/Makefile.dx


# Only the doxygen directory may be built, cleaned, etc
.PHONY: all clean
all clean:
	@$(MAKE) -C html $@

