//
// vga.hpp
//
// Various VGA constants and definitions.  These are standard
// values as defined by the VGA specification; these are not
// specific to any particular hardware or VGA implementation.
//

#ifndef _VGA_HPP
#define _VGA_HPP


//
// Although the default VGA palette supports 16 colors, the driver
// just displays all text as white characters on a black background
//
#define		VGA_TEXT_ATTRIBUTE_BLACK_ON_BLACK	0x0		// Blank line/screen
#define		VGA_TEXT_ATTRIBUTE_WHITE_ON_BLACK	0x7		// Normal text


//
// Two bytes of storage per character: one byte for the character
// itself, plus a second byte to describe the character attributes
// (e.g., color, blinking, etc).
//
#define		VGA_TEXT_BYTES_PER_CHARACTER		2


//
// Base addresses for the VGA Display Memory; the Display Memory is
// accessible at one of these addresses in host memory.  The driver
// can select between the different addresses based on the values
// programmed into the Miscellaneous register in the set of Graphics
// Control registers.
//
#define		VGA_MEMORY_BASE_ADDRESS_A0000		0xA0000
#define		VGA_MEMORY_BASE_ADDRESS_B0000		0xB0000
#define		VGA_MEMORY_BASE_ADDRESS_B8000		0xB8000


//
// The VGS is (typically?) in "mode 3" at boot time: 80x25 text, based at
// physical 0xB8000
//
#define		VGA_TEXT_BASE_ADDRESS				VGA_MEMORY_BASE_ADDRESS_B8000
#define		VGA_TEXT_COLUMN_COUNT				80
#define		VGA_TEXT_ROW_COUNT					25

#define		VGA_TEXT_LINE_SIZE					VGA_TEXT_COLUMN_COUNT * \
												VGA_TEXT_BYTES_PER_CHARACTER

#define		VGA_TEXT_MEMORY_SIZE				VGA_TEXT_LINE_SIZE * \
												VGA_TEXT_ROW_COUNT



//
// Various offsets into the frame buffer
//
#define		VGA_TEXT_FIRST_LINE_OFFSET			0
#define		VGA_TEXT_SECOND_LINE_OFFSET			VGA_TEXT_LINE_SIZE
#define		VGA_TEXT_LAST_LINE_OFFSET			((VGA_TEXT_ROW_COUNT-1) * \
												VGA_TEXT_LINE_SIZE)
#define		VGA_TEXT_OVERFLOW_LINE_OFFSET		(VGA_TEXT_LAST_LINE_OFFSET + \
												VGA_TEXT_LINE_SIZE)



//
// Port addresses for VGA controller.  The VGA registers are
// divided into six groups: Attribute Control, CRT Control (CRTC),
// General/External, Graphics Control, Palette and Sequencer registers.
//
// Some of the internal hardware registers are accessed indirectly using
// a dedicated Address port to indicate the desired register.  Other
// ports are asymmetric: reading the port will return the contents of
// register X, but writing to the same port will update register Y.
//
#define		VGA_ATTRIBUTE_3C0_PORT_ADDRESS			0x3C0
#define		VGA_ATTRIBUTE_3C1_PORT_ADDRESS			0x3C1

#define		VGA_CRTC_ADDRESS_PORT_ADDRESS			0x3D4
#define		VGA_CRTC_DATA_PORT_ADDRESS				0x3D5

#define		VGA_GENERAL_3C2_PORT_ADDRESS			0x3C2
#define		VGA_GENERAL_3CA_PORT_ADDRESS			0x3CA
#define		VGA_GENERAL_3CC_PORT_ADDRESS			0x3CC
#define		VGA_GENERAL_3DA_PORT_ADDRESS			0x3DA

#define		VGA_GRAPHICS_ADDRESS_PORT_ADDRESS		0x3CE
#define		VGA_GRAPHICS_DATA_PORT_ADDRESS			0x3CF

#define		VGA_PALETTE_WRITE_ADDRESS_PORT_ADDRESS	0x3C8
#define		VGA_PALETTE_READ_ADDRESS_PORT_ADDRESS	0x3C7
#define		VGA_PALETTE_DATA_PORT_ADDRESS			0x3C9
#define		VGA_PALETTE_PEL_MASK_PORT_ADDRESS		0x3C6

#define		VGA_SEQUENCER_ADDRESS_PORT_ADDRESS		0x3C4
#define		VGA_SEQUENCER_DATA_PORT_ADDRESS			0x3C5


//
// Register offsets.  Software cannot access most of the VGA registers
// directly, but must load an offset into the appropriate Address
// register to specify the actual target register.  The Attribute,
// CRTC, Graphics and Sequencer registers all behave in this fashion.
//
#define		VGA_ATTRIBUTE_PALETTE_0_REGISTER			0x00
#define		VGA_ATTRIBUTE_PALETTE_1_REGISTER			0x01
#define		VGA_ATTRIBUTE_PALETTE_2_REGISTER			0x02
#define		VGA_ATTRIBUTE_PALETTE_3_REGISTER			0x03
#define		VGA_ATTRIBUTE_PALETTE_4_REGISTER			0x04
#define		VGA_ATTRIBUTE_PALETTE_5_REGISTER			0x05
#define		VGA_ATTRIBUTE_PALETTE_6_REGISTER			0x06
#define		VGA_ATTRIBUTE_PALETTE_7_REGISTER			0x07
#define		VGA_ATTRIBUTE_PALETTE_8_REGISTER			0x08
#define		VGA_ATTRIBUTE_PALETTE_9_REGISTER			0x09
#define		VGA_ATTRIBUTE_PALETTE_10_REGISTER			0x0A
#define		VGA_ATTRIBUTE_PALETTE_11_REGISTER			0x0B
#define		VGA_ATTRIBUTE_PALETTE_12_REGISTER			0x0C
#define		VGA_ATTRIBUTE_PALETTE_13_REGISTER			0x0D
#define		VGA_ATTRIBUTE_PALETTE_14_REGISTER			0x0E
#define		VGA_ATTRIBUTE_PALETTE_15_REGISTER			0x0F
#define		VGA_ATTRIBUTE_MODE_REGISTER					0x10
#define		VGA_ATTRIBUTE_OVERSCAN_REGISTER				0x11
#define		VGA_ATTRIBUTE_COLOR_PLANE_REGISTER			0x12
#define		VGA_ATTRIBUTE_PIXEL_PANNING_REGISTER		0x13
#define		VGA_ATTRIBUTE_COLOR_SELECT_REGISTER			0x14

#define		VGA_CRTC_HORIZONTAL_TOTAL_REGISTER			0x00
#define		VGA_CRTC_HORIZONTAL_DISPLAY_END_REGISTER	0x01
#define		VGA_CRTC_START_HORIZONTAL_BLANKING_REGISTER	0x02
#define		VGA_CRTC_END_HORIZONTAL_BLANKING_REGISTER	0x03
#define		VGA_CRTC_START_HORIZONTAL_RETRACE_REGISTER	0x04
#define		VGA_CRTC_END_HORIZONTAL_RETRACE_REGISTER	0x05
#define		VGA_CRTC_VERTICAL_TOTAL_REGISTER			0x06
#define		VGA_CRTC_OVERFLOW_REGISTER					0x07
#define		VGA_CRTC_ROW_SCAN_REGISTER					0x08
#define		VGA_CRTC_MAX_SCAN_LINE_REGISTER				0x09
#define		VGA_CRTC_CURSOR_START_REGISTER				0x0A
#define		VGA_CRTC_CURSOR_END_REGISTER				0x0B
#define		VGA_CRTC_START_ADDRESS_HIGH_REGISTER		0x0C
#define		VGA_CRTC_START_ADDRESS_LOW_REGISTER			0x0D
#define		VGA_CRTC_CURSOR_LOCATION_HIGH_REGISTER		0x0E
#define		VGA_CRTC_CURSOR_LOCATION_LOW_REGISTER		0x0F
#define		VGA_CRTC_VERTICAL_RETRACE_START_REGISTER	0x10
#define		VGA_CRTC_VERTICAL_RETRACE_END_REGISTER		0x11
#define		VGA_CRTC_VERTICAL_DISPLAY_END_REGISTER		0x12
#define		VGA_CRTC_OFFSET_REGISTER					0x13
#define		VGA_CRTC_UNDERLINE_LOCATION_REGISTER		0x14
#define		VGA_CRTC_START_VERTICAL_BLANK_REGISTER		0x15
#define		VGA_CRTC_END_VERTICAL_BLANK_REGISTER		0x16
#define		VGA_CRTC_MODE_CONTROL_REGISTER				0x17
#define		VGA_CRTC_LINE_COMPARE_REGISTER				0x18

#define		VGA_GRAPHICS_SET_RESET_REGISTER				0x00
#define		VGA_GRAPHICS_ENABLE_SET_RESET_REGISTER		0x01
#define		VGA_GRAPHICS_COLOR_COMPARE_REGISTER			0x02
#define		VGA_GRAPHICS_DATA_ROTATE_REGISTER			0x03
#define		VGA_GRAPHICS_READ_MAP_REGISTER				0x04
#define		VGA_GRAPHICS_MODE_REGISTER					0x05
#define		VGA_GRAPHICS_MISC_REGISTER					0x06
#define		VGA_GRAPHICS_COLOR_DONT_CARE_REGISTER		0x07
#define		VGA_GRAPHICS_BIT_MASK_REGISTER				0x08

#define		VGA_SEQUENCER_RESET_REGISTER				0x00
#define		VGA_SEQUENCER_CLOCKING_REGISTER				0x01
#define		VGA_SEQUENCER_MASK_REGISTER					0x02
#define		VGA_SEQUENCER_CHARACTER_MAP_REGISTER		0x03
#define		VGA_SEQUENCER_MEMORY_REGISTER				0x04


//
// Bit definitions for the Attribute Control registers.  EGA-only bits
// are not included here.
//
#define		VGA_ATTRIBUTE_ADDRESS_ALLOW_HOST					0x00
#define		VGA_ATTRIBUTE_ADDRESS_ALLOW_DISPLAY					0x20

#define		VGA_ATTRIBUTE_PALETTE_SECONDARY_RED_ABSENT			0x00
#define		VGA_ATTRIBUTE_PALETTE_SECONDARY_RED_PRESENT			0x20
#define		VGA_ATTRIBUTE_PALETTE_SECONDARY_GREEN_ABSENT		0x00
#define		VGA_ATTRIBUTE_PALETTE_SECONDARY_GREEN_PRESENT		0x10
#define		VGA_ATTRIBUTE_PALETTE_SECONDARY_BLUE_ABSENT			0x00
#define		VGA_ATTRIBUTE_PALETTE_SECONDARY_BLUE_PRESENT		0x08
#define		VGA_ATTRIBUTE_PALETTE_RED_ABSENT					0x00
#define		VGA_ATTRIBUTE_PALETTE_RED_PRESENT					0x04
#define		VGA_ATTRIBUTE_PALETTE_GREEN_ABSENT					0x00
#define		VGA_ATTRIBUTE_PALETTE_GREEN_PRESENT					0x02
#define		VGA_ATTRIBUTE_PALETTE_BLUE_ABSENT					0x00
#define		VGA_ATTRIBUTE_PALETTE_BLUE_PRESENT					0x01

#define		VGA_ATTRIBUTE_MODE_USE_COLOR_REGISTER				0x80
#define		VGA_ATTRIBUTE_MODE_USE_PALETTE_REGISTER				0x00
#define		VGA_ATTRIBUTE_MODE_PIXEL_CLOCK_EVERY_CYCLE			0x00
#define		VGA_ATTRIBUTE_MODE_PIXEL_CLOCK_EVERY_OTHER_CYCLE	0x40
#define		VGA_ATTRIBUTE_MODE_PIXEL_PANNING_NORMAL				0x20
#define		VGA_ATTRIBUTE_MODE_PIXEL_PANNING_WAIT_FOR_SYNCH		0x00
#define		VGA_ATTRIBUTE_MODE_BLINK_DISABLE					0x00
#define		VGA_ATTRIBUTE_MODE_BLINK_ENABLE						0x08
#define		VGA_ATTRIBUTE_MODE_CHARACTER_CODE_BIT8_EXTEND		0x04
#define		VGA_ATTRIBUTE_MODE_CHARACTER_CODE_BIT9_BACKGROUND	0x00
#define		VGA_ATTRIBUTE_MODE_DISPLAY_COLOR_EMULATION			0x00
#define		VGA_ATTRIBUTE_MODE_DISPLAY_MONOCHROME_EMULATION		0x02
#define		VGA_ATTRIBUTE_MODE_ALPHANUMERIC						0x00
#define		VGA_ATTRIBUTE_MODE_GRAPHICS							0x01

#define		VGA_ATTRIBUTE_OVERSCAN_SECONDARY_RED_ABSENT			0x00
#define		VGA_ATTRIBUTE_OVERSCAN_SECONDARY_RED_PRESENT		0x20
#define		VGA_ATTRIBUTE_OVERSCAN_SECONDARY_GREEN_ABSENT		0x00
#define		VGA_ATTRIBUTE_OVERSCAN_SECONDARY_GREEN_PRESENT		0x10
#define		VGA_ATTRIBUTE_OVERSCAN_SECONDARY_BLUE_ABSENT		0x00
#define		VGA_ATTRIBUTE_OVERSCAN_SECONDARY_BLUE_PRESENT		0x08
#define		VGA_ATTRIBUTE_OVERSCAN_RED_ABSENT					0x00
#define		VGA_ATTRIBUTE_OVERSCAN_RED_PRESENT					0x04
#define		VGA_ATTRIBUTE_OVERSCAN_GREEN_ABSENT					0x00
#define		VGA_ATTRIBUTE_OVERSCAN_GREEN_PRESENT				0x02
#define		VGA_ATTRIBUTE_OVERSCAN_BLUE_ABSENT					0x00
#define		VGA_ATTRIBUTE_OVERSCAN_BLUE_PRESENT					0x01

#define		VGA_ATTRIBUTE_COLOR_PLANE_ENABLE_PLANE_0			0x01
#define		VGA_ATTRIBUTE_COLOR_PLANE_ENABLE_PLANE_1			0x02
#define		VGA_ATTRIBUTE_COLOR_PLANE_ENABLE_PLANE_2			0x04
#define		VGA_ATTRIBUTE_COLOR_PLANE_ENABLE_PLANE_3			0x08

#define		VGA_ATTRIBUTE_COLOR_SELECT_ADDRESS_BITS_4_5_MASK	0x03
#define		VGA_ATTRIBUTE_COLOR_SELECT_ADDRESS_BITS_4_5_SHIFT	0x00
#define		VGA_ATTRIBUTE_COLOR_SELECT_ADDRESS_BITS_6_7_MASK	0x03
#define		VGA_ATTRIBUTE_COLOR_SELECT_ADDRESS_BITS_6_7_SHIFT	0x02


//
// Bit definitions for the CRT Control registers.  EGA-only bits
// are not included here.
//
#define		VGA_CRTC_END_HORIZONTAL_BLANKING_DISABLE_RETRACE_ACCESS	0x00
#define		VGA_CRTC_END_HORIZONTAL_BLANKING_ENABLE_RETRACE_ACCESS	0x80
#define		VGA_CRTC_END_HORIZONTAL_BLANKING_SKEW_MASK				0x03
#define		VGA_CRTC_END_HORIZONTAL_BLANKING_SKEW_SHIFT				0x05
#define		VGA_CRTC_END_HORIZONTAL_BLANKING_END_BLANKING_MASK_LOW	0x1F
#define		VGA_CRTC_END_HORIZONTAL_BLANKING_END_BLANKING_SHIFT		0x00

#define		VGA_CRTC_END_HORIZONTAL_RETRACE_END_BLANKING_MASK_HIGH	0x01
#define		VGA_CRTC_END_HORIZONTAL_RETRACE_END_BLANKING_SHIFT		0x07
#define		VGA_CRTC_END_HORIZONTAL_RETRACE_RETRACE_DELAY_MASK		0x03
#define		VGA_CRTC_END_HORIZONTAL_RETRACE_RETRACE_DELAY_SHIFT		0x05
#define		VGA_CRTC_END_HORIZONTAL_RETRACE_END_RETRACE_MASK		0x1F
#define		VGA_CRTC_END_HORIZONTAL_RETRACE_END_RETRACE_SHIFT		0x00

#define		VGA_CRTC_OVERFLOW_VERTICAL_RETRACE_START9				0x80
#define		VGA_CRTC_OVERFLOW_VERTICAL_DISPLAY_ENABLE_END9			0x40
#define		VGA_CRTC_OVERFLOW_VERTICAL_TOTAL9						0x20
#define		VGA_CRTC_OVERFLOW_LINE_COMPARE9							0x10
#define		VGA_CRTC_OVERFLOW_START_VERTICAL_BLANKING8				0x08
#define		VGA_CRTC_OVERFLOW_VERTICAL_RETRACE_START8				0x04
#define		VGA_CRTC_OVERFLOW_VERTICAL_DISPLAY_ENABLE_END8			0x02
#define		VGA_CRTC_OVERFLOW_VERTICAL_TOTAL8						0x01

#define		VGA_CRTC_ROW_SCAN_BYTE_PANNING_MASK						0x03
#define		VGA_CRTC_ROW_SCAN_BYTE_PANNING_SHIFT					0x05
#define		VGA_CRTC_ROW_SCAN_PRESET_ROW_SCAN_MASK					0x1F
#define		VGA_CRTC_ROW_SCAN_PRESET_ROW_SCAN_SHIFT					0x00

#define		VGA_CRTC_MAX_SCAN_LINE_SCALE_TO_400_SCAN_LINES			0x80
#define		VGA_CRTC_MAX_SCAN_LINE_ENABLE_200_SCAN_LINES			0x00
#define		VGA_CRTC_MAX_SCAN_LINE_LINE_COMPARE9					0x40
#define		VGA_CRTC_MAX_SCAN_LINE_START_VERTICAL_BLANKING9			0x20
#define		VGA_CRTC_MAX_SCAN_LINE_MAX_SCAN_LINE_MASK				0x1F
#define		VGA_CRTC_MAX_SCAN_LINE_MAX_SCAN_LINE_SHIFT				0x00

#define		VGA_CRTC_CURSOR_START_ENABLE_CURSOR						0x00
#define		VGA_CRTC_CURSOR_START_DISABLE_CURSOR					0x20
#define		VGA_CRTC_CURSOR_START_SCAN_LINE_MASK					0x1F
#define		VGA_CRTC_CURSOR_START_SCAN_LINE_SHIFT					0x00

#define		VGA_CRTC_CURSOR_END_CURSOR_SKEW_MASK					0x03
#define		VGA_CRTC_CURSOR_END_CURSOR_SKEW_SHIFT					0x05
#define		VGA_CRTC_CURSOR_END_SCAN_LINE_MASK						0x1F
#define		VGA_CRTC_CURSOR_END_SCAN_LINE_SHIFT						0x00

#define		VGA_CRTC_VERTICAL_RETRACE_END_READ_ONLY_REGISTERS		0x80
#define		VGA_CRTC_VERTICAL_RETRACE_END_READ_WRITE_REGISTERS		0x00
#define		VGA_CRTC_VERTICAL_RETRACE_END_3_REFRESH_CYCLES_PER_LINE	0x00
#define		VGA_CRTC_VERTICAL_RETRACE_END_5_REFRESH_CYCLES_PER_LINE	0x40
#define		VGA_CRTC_VERTICAL_RETRACE_END_PERIOD_END_MASK			0x0F
#define		VGA_CRTC_VERTICAL_RETRACE_END_PERIOD_END_SHIFT			0x00

#define		VGA_CRTC_UNDERLINE_LOCATION_DOUBLE_WORD_ADDRESSING		0x40
#define		VGA_CRTC_UNDERLINE_LOCATION_NORMAL_WORD_ADDRESSING		0x00
#define		VGA_CRTC_UNDERLINE_LOCATION_NORMAL_CLOCK				0x00
#define		VGA_CRTC_UNDERLINE_LOCATION_ONE_QUARTER_CLOCK			0x20
#define		VGA_CRTC_UNDERLINE_LOCATION_SCAN_LINE_MASK				0x1F
#define		VGA_CRTC_UNDERLINE_LOCATION_SCAN_LINE_SHIFT				0x00

#define		VGA_CRTC_END_VERTICAL_BLANK_MASK						0x7F
#define		VGA_CRTC_END_VERTICAL_BLANK_SHIFT						0x00

#define		VGA_CRTC_MODE_CONTROL_DISABLE_RETRACE			   		0x00
#define		VGA_CRTC_MODE_CONTROL_ENABLE_RETRACE			   		0x80
#define		VGA_CRTC_MODE_CONTROL_BYTE_MODE					   		0x40
#define		VGA_CRTC_MODE_CONTROL_WORD_MODE					   		0x00
#define		VGA_CRTC_MODE_CONTROL_LEAST_SIGNIFICANT_BIT_13	   		0x00
#define		VGA_CRTC_MODE_CONTROL_LEAST_SIGNIFICANT_BIT_15	   		0x20
#define		VGA_CRTC_MODE_CONTROL_COUNT_EVERY_CLOCK			   		0x00
#define		VGA_CRTC_MODE_CONTROL_COUNT_EVERY_OTHER_CLOCK	   		0x08
#define		VGA_CRTC_MODE_CONTROL_HORIZONTAL_REFRESH_1024_LINES		0x00
#define		VGA_CRTC_MODE_CONTROL_HORIZONTAL_REFRESH_2048_LINES		0x04
#define		VGA_CRTC_MODE_CONTROL_ROW_SCAN_COUNTER_SOURCE			0x00
#define		VGA_CRTC_MODE_CONTROL_ADDRESS_COUNTER_SOURCE			0x02
#define		VGA_CRTC_MODE_CONTROL_CGA_COMPATIBILITY					0x00
#define		VGA_CRTC_MODE_CONTROL_NORMAL_OPERATION					0x01


//
// Bit definitions for the General registers.  EGA-only bits
// are not included here.
//
#define		VGA_GENERAL_MISC_VERTICAL_SYNC_POLARITY		0x80
#define		VGA_GENERAL_MISC_HORIZONTAL_SYNC_POLARITY	0x40
#define		VGA_GENERAL_MISC_HIGH_PAGE					0x20
#define		VGA_GENERAL_MISC_LOW_PAGE					0x00
#define		VGA_GENERAL_MISC_25MHZ_CLOCK				0x00
#define		VGA_GENERAL_MISC_28MHZ_CLOCK				0x04
#define		VGA_GENERAL_MISC_DISABLE_VIDEO_RAM			0x00
#define		VGA_GENERAL_MISC_ENABLE_VIDEO_RAM			0x02
#define		VGA_GENERAL_MISC_COLOR_EMULATION			0x01
#define		VGA_GENERAL_MISC_MONOCHROME_EMULATION		0x00

#define		VGA_GENERAL_FEATURE_NORMAL_VERTICAL_SYNC	0x04
#define		VGA_GENERAL_FEATURE_SYNC_OR_DISPLAY			0x00

#define		VGA_GENERAL_STATUS0_SWITCH_SENSE_OFF		0x00
#define		VGA_GENERAL_STATUS0_SWITCH_SENSE_ON			0x10

#define		VGA_GENERAL_STATUS1_IDLE					0x00
#define		VGA_GENERAL_STATUS1_VERTICAL_RETRACE		0x08
#define		VGA_GENERAL_STATUS1_EITHER_RETRACE			0x01


//
// Bit definitions for the Graphics Control registers.  EGA-only bits
// are not included here.
//
#define		VGA_GRAPHICS_SET_RESET_PLANE_0				0x01
#define		VGA_GRAPHICS_SET_RESET_PLANE_1				0x02
#define		VGA_GRAPHICS_SET_RESET_PLANE_2				0x04
#define		VGA_GRAPHICS_SET_RESET_PLANE_3				0x08

#define		VGA_GRAPHICS_ENABLE_SET_RESET_PLANE_0		0x01
#define		VGA_GRAPHICS_ENABLE_SET_RESET_PLANE_1		0x02
#define		VGA_GRAPHICS_ENABLE_SET_RESET_PLANE_2		0x04
#define		VGA_GRAPHICS_ENABLE_SET_RESET_PLANE_3		0x08

#define		VGA_GRAPHICS_COLOR_COMPARE_PLANE_0			0x01
#define		VGA_GRAPHICS_COLOR_COMPARE_PLANE_1			0x02
#define		VGA_GRAPHICS_COLOR_COMPARE_PLANE_2			0x04
#define		VGA_GRAPHICS_COLOR_COMPARE_PLANE_3			0x08

#define		VGA_GRAPHICS_DATA_ROTATE_ORIGINAL_DATA		0x00
#define		VGA_GRAPHICS_DATA_ROTATE_AND_DATA			0x10
#define		VGA_GRAPHICS_DATA_ROTATE_OR_DATA			0x20
#define		VGA_GRAPHICS_DATA_ROTATE_XOR_DATA			0x30
#define		VGA_GRAPHICS_DATA_ROTATE_ROTATE_COUNT_MASK	0x0F
#define		VGA_GRAPHICS_DATA_ROTATE_ROTATE_COUNT_SHIFt	0x00

#define		VGA_GRAPHICS_READ_MAP_PLANE_0				0x00
#define		VGA_GRAPHICS_READ_MAP_PLANE_1				0x01
#define		VGA_GRAPHICS_READ_MAP_PLANE_2				0x02
#define		VGA_GRAPHICS_READ_MAP_PLANE_3				0x03

#define		VGA_GRAPHICS_MODE_SHIFT_CGA_COMPATIBLE		0x20
#define		VGA_GRAPHICS_MODE_SHIFT_VGA_DEFAULT			0x00
#define		VGA_GRAPHICS_MODE_ODD_EVEN_CGA_COMPATIBLE	0x10
#define		VGA_GRAPHICS_MODE_ODD_EVEN_VGA_DEFAULT		0x00
#define		VGA_GRAPHICS_MODE_READ_MODE_0				0x00
#define		VGA_GRAPHICS_MODE_READ_MODE_1				0x08
#define		VGA_GRAPHICS_MODE_WRITE_MODE_0				0x00
#define		VGA_GRAPHICS_MODE_WRITE_MODE_1				0x01
#define		VGA_GRAPHICS_MODE_WRITE_MODE_2				0x02
#define		VGA_GRAPHICS_MODE_WRITE_MODE_3				0x03

#define		VGA_GRAPHICS_MISC_MEMORY_FULL_VGA			0x00
#define		VGA_GRAPHICS_MISC_MEMORY_SHARED_VGA			0x01
#define		VGA_GRAPHICS_MISC_MEMORY_HERCULES_EMULATION	0x02
#define		VGA_GRAPHICS_MISC_MEMORY_CGA_EMULATION		0x03
#define		VGA_GRAPHICS_MISC_ODD_EVEN_VGA_DEFAULT		0x00
#define		VGA_GRAPHICS_MISC_ODD_EVEN_MDA_EMULATION	0x02
#define		VGA_GRAPHICS_MISC_MODE_ALPHANUMERIC			0x00
#define		VGA_GRAPHICS_MISC_MODE_GRAPHICS				0x01

#define		VGA_GRAPHICS_COLOR_DONT_CARE_PLANE_0		0x01
#define		VGA_GRAPHICS_COLOR_DONT_CARE_PLANE_1		0x02
#define		VGA_GRAPHICS_COLOR_DONT_CARE_PLANE_2		0x04
#define		VGA_GRAPHICS_COLOR_DONT_CARE_PLANE_3		0x08


//
// Bit definitions for the Palette registers.  The Palette registers are
// specific to the VGA.
//
#define		VGA_PALETTE_STATE_READ_IN_PROGRESS			0x00
#define		VGA_PALETTE_STATE_WRITE_IN_PROGRESS			0x03


//
// Bit definitions for the Sequencer registers.  EGA-only bits
// are not included here.
//
#define		VGA_SEQUENCER_RESET_SYNCHRONOUS_RESET_START	0x00
#define		VGA_SEQUENCER_RESET_SYNCHRONOUS_RESET_STOP	0x01

#define		VGA_SEQUENCER_CLOCKING_SCREEN_OFF			0x20
#define		VGA_SEQUENCER_CLOCKING_SCREEN_ON			0x00
#define		VGA_SEQUENCER_CLOCKING_LOAD_ON_EVERY_CYCLE	0x00
#define		VGA_SEQUENCER_CLOCKING_LOAD_ON_FOURTH_CYCLE	0x10
#define		VGA_SEQUENCER_CLOCKING_HALF_MASTER_CLOCK	0x08
#define		VGA_SEQUENCER_CLOCKING_MASTER_CLOCK			0x00
#define		VGA_SEQUENCER_CLOCKING_LOAD_ON_SECOND_CYCLE	0x04
#define		VGA_SEQUENCER_CLOCKING_8DOTS_PER_CHAR		0x01
#define		VGA_SEQUENCER_CLOCKING_9DOTS_PER_CHAR		0x00

#define		VGA_SEQUENCER_MASK_DISABLE_PLANE_3			0x00
#define		VGA_SEQUENCER_MASK_ENABLE_PLANE_3			0x08
#define		VGA_SEQUENCER_MASK_DISABLE_PLANE_2			0x00
#define		VGA_SEQUENCER_MASK_ENABLE_PLANE_2			0x04
#define		VGA_SEQUENCER_MASK_DISABLE_PLANE_1			0x00
#define		VGA_SEQUENCER_MASK_ENABLE_PLANE_1			0x02
#define		VGA_SEQUENCER_MASK_DISABLE_PLANE_0			0x00
#define		VGA_SEQUENCER_MASK_ENABLE_PLANE_0			0x01

			//@might want to combine these into single/simpler masks
#define		VGA_SEQUENCER_CHARACTER_MAP_GENERATOR_A_HIGH	0x20
#define		VGA_SEQUENCER_CHARACTER_MAP_GENERATOR_B_HIGH	0x10
#define		VGA_SEQUENCER_CHARACTER_MAP_GENERATOR_A_LOW		0x0C
#define		VGA_SEQUENCER_CHARACTER_MAP_GENERATOR_B_LOW		0x03

#define		VGA_SEQUENCER_MEMORY_CHAIN_PLANES			0x08
#define		VGA_SEQUENCER_MEMORY_SELECT_PLANES			0x00
#define		VGA_SEQUENCER_MEMORY_ODD_EVEN_ADDRESSING	0x00
#define		VGA_SEQUENCER_MEMORY_SEQUENTIAL_ADDRESSING	0x04
#define		VGA_SEQUENCER_MEMORY_NO_EXTENDED_MEMORY		0x00
#define		VGA_SEQUENCER_MEMORY_USE_EXTENDED_MEMORY	0x02


#endif
