#
# Makefile.common
#
# Custom build settings that apply to all common components.  Values here
# replace or modify the default settings in Makefile.dx
#


#
# Inherit the default settings
#
include $(DX_ROOT_DIR)/src/Makefile.src



#
# The root of the "common" tree
#
DX_COMMON_DIR	:= $(DX_SRC_DIR)/common


#
# Default tool settings
#
ASM_INCLUDES	+= -I$(DX_COMMON_DIR)/inc
